# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180905_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default=1, max_length=30, verbose_name='name'),
            preserve_default=False,
        ),
    ]
