# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.CharField(default=12, max_length=30, verbose_name='name'),
            preserve_default=False,
        ),
    ]
