version: '2'
services:
  db:
    image: mysql:5.7.21
    environment:
      - MYSQL_DATABASE=phase
      - MYSQL_ROOT_PASSWORD=123456
    restart: always
    ports:
      - "3306:3306"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    restart: always
    ports:
      - "8001:8001"
    depends_on:
      - db
