# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 06:16
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='\u6807\u9898')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='\u535a\u5ba2\u6807\u7b7e')),
                ('jianshu', models.CharField(blank=True, max_length=200, verbose_name='\u6982\u8981')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='\u6587\u7ae0\u6b63\u6587')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u8868\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('password', models.TextField(verbose_name='password')),
            ],
        ),
    ]
